---
title: "Five Decades of Global Terrorism"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    css: styles.css
    social: [ "twitter"]
    source_code: embed
runtime: shiny
---


```{r global, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(hrbrthemes)
library(ggsci)
library(maps)
library(ggthemes)
library(gganimate)
library(shiny)
library(shinyWidgets)
library(highcharter)

df <- read_csv("global_terror_clean.csv") 

load("mapdata.Rdata")

theme_terr <- function() { 
  theme_modern_rc(plot_title_size = 30) %+replace% 
    theme(
      plot.title = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      legend.position = "none",
      axis.text.x = element_text(size = 18),
      axis.text.y = element_text(size = 18,hjust=1)
    )
}

theme_set(theme_terr())
```


Overview 
=======================================================================

Data source: National Consortium for the Study of Terrorism and Responses to Terrorism (START). (2018). Global Terrorism Database.

Row
-----------------------------------------------------------------------

### Number of attacks { .colored_smallbox}

```{r }
n_attacks <- nrow(df)
n_attacks <- format(n_attacks,big.mark   = ",")
valueBox(n_attacks, icon = "fa-fire")
```

### Number of casualties { .colored_smallbox }

```{r }
n_kills <- sum(df$nkill,na.rm=T)
n_kills <- format(n_kills,big.mark   = ",")
valueBox(n_kills, icon = "ion-man")
```

### % Succesful attacks { .colored }

```{r }
pct <- round(nrow(df[df$success==1,]) / nrow(df) *100,2)
gauge(pct, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(0, 1.0), warning = c(1.1, 2), danger = c(2.1, 100),
  colors = "darkred"
))
```

Row
-----------------------------------------------------------------------

### Number of attacks by year { .colored }

```{r }
df %>%
  group_by(year) %>%
  count() %>%
  ggplot(aes(year,n)) +
  geom_line(colour="darkred", size = 1) +
  scale_y_continuous(labels = function(n) {
    trans = n / 1000
    paste0(trans, "K")
  })
```

### Number of kills by year { .colored }

```{r }
df %>%
  group_by(year) %>%
  summarise(n = sum(nkill,na.rm=T)) %>%
  ggplot(aes(year,n)) +
  geom_line(colour="darkred", size = 1) +
  scale_y_continuous(labels = function(n) {
    trans = n / 1000
    paste0(trans, "K")
  })
```


Attack info 
=======================================================================

Row
-----

### Most used weapons { .colored}

```{r }
df %>%
  mutate(weaptype1_txt = recode(weaptype1_txt,"Vehicle (not to include vehicle-borne explosives, i.e., car or truck bombs)" 
="Vehicle")) %>%
  group_by(weaptype1_txt) %>%
  count() %>%
  arrange(desc(n)) %>%
  ungroup() %>%
  top_n(10) %>%
  mutate(pct = n/sum(n)*100) %>%
  ggplot(aes(reorder(weaptype1_txt,pct),pct, fill = pct)) +
  geom_col(colour=NA) +
  scale_fill_material("red") +
  scale_y_percent(scale=1) +
  coord_flip()
```

### Most common attack types { .colored}

```{r }
df %>%
  group_by(attacktype1_txt) %>%
  count() %>%
  ungroup() %>%
  top_n(10) %>%
  mutate(attacktype1_txt = recode(attacktype1_txt, 
        "Facility/Infrastructure Attack" = "Facility/Infrastr.", 
        "Hostage Taking (Barricade Incident)" = "Hostage Taking",
        "Hostage Taking (Kidnapping)" = "Kidnapping"),
         pct = n/sum(n)*100) %>%
  ggplot(aes(reorder(attacktype1_txt,pct),pct, fill = pct)) +
  geom_col(colour=NA) +
  scale_fill_material("red") +
  scale_y_percent(scale=1) +
  coord_flip()
```

### Most common targets {.colored}

```{r }
df %>%
  filter(!is.na(target1)) %>%
  group_by(target1) %>%
  count() %>%
  arrange(desc(n)) %>%
  ungroup() %>%
  top_n(10) %>%
  mutate(pct = n/sum(n)*100) %>%
  ggplot(aes(reorder(target1,pct),pct, fill = log(pct))) +
  geom_col(colour=NA) +
  scale_fill_material("red") +
  scale_y_percent(scale=1) +
  coord_flip()
```

Row
---
### Attacks in history with the most casualties  {.colored}

```{r fig.width=15, fig.height=7}
df %>%
  mutate(id = paste(year,city,country_txt,"-",attacktype1_txt)) %>%
  select(date,id,nkill,nwound) %>%
  distinct(id, .keep_all = T) %>%
  arrange(desc(nkill)) %>%
  top_n(15,nkill) %>%
  ggplot(aes(x = reorder(id,nkill),y=nkill,fill=log(nkill))) +
  geom_col(colour=NA) +
  coord_flip() +
  scale_fill_material("red")
```

Interactive map 
=======================================================================

Column {.sidebar data-width=200}
-----------------------------------------------------------------------
<br>
Select a year and explore the data by hovering over locations
<br>
<br>
```{r}
chooseSliderSkin("Nice")
sliderInput("year_select", label = "Year",
            min = min(df$year), max(df$year), min(df$year), step = 1,sep = "")
```


Column
--- 
### Global attacks through time { .colored}
```{r fig.height=15, fig.width=18}

renderHighchart({
  
d <- df %>% 
  filter(nkill>0,year == input$year_select) %>%
  select(country_txt,city,attacktype1_txt,longitude,latitude,nkill,summary) %>%
  mutate(location = glue::glue("{city}, {country_txt}"),
         summary = ifelse(is.na(summary),"none",summary),
         lat=latitude,
         lon=longitude,
         z = nkill) %>%
  select(location,attacktype1_txt,lat,lon,z,summary)

x <- c("Location", "Attack type", "Casualties","Summary")
y <- c("{point.location}", "{point.attacktype1_txt}", "{point.z}", "\n{point.summary}")
tltip <- tooltip_table(x,y)

mapdata %>%
  hc_add_series(data = d,
                type = "mapbubble",
                name="attack info",maxSize = '4%',
                color="darkred") %>% 
  hc_mapNavigation(enabled = TRUE) %>%
  hc_chart(backgroundColor = "#1E1E1E") %>%
  hc_legend(enabled = F) %>%
  hc_tooltip(useHTML = TRUE, headerFormat = "", pointFormat = tltip) 

})
```
